server:
  port: 8084
  contextPath: /

featr:
  version: @project.version@
  adminPassword: 2change
  testTypes:
    - functional
    - performance
    - security
  testLevels:
    - unit
    - integration
    - end-to-end
  repositories:
    id001:
      remote: git@server:/repositories/dctnry.git
      local: /repos/dctnry
    id002:
      remote: git@server:/repositories/dctnry-client.git
      local: /repos/front-end

  testSets:
    - id: dictionary
      repository: id001
      testFileType: gherkin
      regExp: .*\.feature$
      type: functional
      level: integration
    - id: front-end-unit
      repository: id002
      testFileType: javascript
      regExp: src/test/.*\.spec\.js$
      type: functional
      level: unit
    - id: front-end-integration
      repository: id002
      testFileType: javascript
      regExp: src/browserTests/.*\.spec\.js$
      type: functional
      level: integration
