server:
  port: 8084
  contextPath: /

featr:
  version: @project.version@
  adminPassword: 2change
  testTypes:
    - functional
    - performance
    - security
  testLevels:
    - unit
    - integration
    - end-to-end
  repositories:
    id001:
      remote: git@server:/repositories/dctnry.git
      local: /repos/Gherkin/testdata/bad
    id002:
      remote: git@server:/repositories/dctnry-client.git
      local: /repos/Gherkin/testdata/good

  testSets:
    - id: bad
      repository: id001
      testFileType: gherkin
      regExp: .*\.feature$
      type: functional
      level: integration
    - id: good
      repository: id002
      testFileType: gherkin
      regExp: .*\.feature$
      type: functional
      level: integration
